# Generated by Django 4.2.5 on 2023-12-22 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recepts.fields
import recepts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Едицу измерения',
                'verbose_name_plural': 'Едицы измерения',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Resipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('preview', recepts.fields.WEBPField(blank=True, null=True, upload_to=recepts.models.image_folder)),
                ('meal_type', models.CharField(blank=True, choices=[('1', 'breakfast'), ('2', 'lunch'), ('3', 'dinner')], max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('cook_time', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, null=True, verbose_name='Шаг')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', recepts.fields.WEBPField(blank=True, null=True, upload_to=recepts.models.image_folder, verbose_name='Фото')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recepts.resipes', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='кол-во')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Название')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='recepts.resipes', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='ResipesLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.resipes', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ResipesIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='кол-во')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Название')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recepts.resipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='ResipesDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.resipes', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Marinades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='кол-во')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Название')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marinades', to='recepts.resipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Маринад',
                'verbose_name_plural': 'Маринады',
            },
        ),
        migrations.CreateModel(
            name='IngredientsBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_blacklist', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_blacklist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
