apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodflow
  template:
    metadata:
      labels:
        app: foodflow
      containers:
        - name: recepts
          image: python:3.8
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "1"
