# Generated by Django 4.2.5 on 2023-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_meal_count_customuser_portions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='meal_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='portions_count',
        ),
    ]
