# Generated by Django 4.2.5 on 2023-11-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepts', '0003_resipeslikes_resipesdislikes_ingredientsblacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsblacklist',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientsblacklist',
            name='ingredients_blacklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsblacklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_blacklist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
