# Generated by Django 4.2.5 on 2023-11-24 16:37

from django.db import migrations, models
import recepts.fields
import recepts.models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0004_remove_ingredientsblacklist_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resipesingredients',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='steps',
            name='photo',
            field=recepts.fields.WEBPField(blank=True, null=True, upload_to=recepts.models.image_folder, verbose_name='Фото'),
        ),
    ]
