# Generated by Django 4.2.5 on 2023-12-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0005_alter_resipesingredients_amount_alter_steps_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
        ),
        migrations.RemoveField(
            model_name='resipesingredients',
            name='dimension',
        ),
    ]
