# Generated by Django 4.2.5 on 2023-12-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0007_resipesingredients_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Название')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='recepts.resipes', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='Marinades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Название')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marinades', to='recepts.resipes', verbose_name='Рецепт')),
            ],
        ),
    ]
