# Generated by Django 4.2.5 on 2023-12-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0008_sauces_marinades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensions',
            options={'ordering': ['number'], 'verbose_name': 'Едицу измерения', 'verbose_name_plural': 'Едицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='marinades',
            options={'verbose_name': 'Маринад', 'verbose_name_plural': 'Маринады'},
        ),
        migrations.AlterModelOptions(
            name='resipesingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='marinades',
            name='amount',
            field=models.FloatField(default=0, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='marinades',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица'),
        ),
        migrations.AlterField(
            model_name='marinades',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='resipesingredients',
            name='amount',
            field=models.FloatField(default=0, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='resipesingredients',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица'),
        ),
        migrations.AlterField(
            model_name='resipesingredients',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='amount',
            field=models.FloatField(default=0, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepts.dimensions', verbose_name='единица'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='состояние'),
        ),
    ]
