# Generated by Django 4.2.5 on 2023-12-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0009_alter_dimensions_options_alter_marinades_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['-name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
