# Generated by Django 4.2.5 on 2023-11-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepts', '0002_alter_resipes_preview_alter_steps_photo'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.AlterModelOptions(
            name='menuconfig',
            options={'verbose_name': 'Настройку меню', 'verbose_name_plural': 'Настройки меню'},
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.DateField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_recipe', to='menu.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.resipes')),
            ],
            options={
                'verbose_name': 'Репт в меню',
                'verbose_name_plural': 'Рецепты в меню',
            },
        ),
    ]
