# Generated by Django 4.2.5 on 2023-12-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
    ]
