# Generated by Django 4.2.5 on 2023-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_shoplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
