# Generated by Django 4.2.5 on 2023-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_shoplist_is_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplist',
            options={'ordering': ['id'], 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AddField(
            model_name='shoplist',
            name='is_sum',
            field=models.BooleanField(default=False),
        ),
    ]
