# Generated by Django 4.2.5 on 2023-12-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_shoplist_options_shoplist_is_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplist',
            options={'ordering': ['id'], 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='is_sum',
        ),
    ]
