# Generated by Django 4.2.5 on 2023-12-29 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_shoplist_options_remove_shoplist_is_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemenu',
            old_name='week_day',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ingredients', to='menu.menu'),
        ),
    ]
