# Generated by Django 4.2.5 on 2023-12-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_week_day_recipemenu_date_alter_shoplist_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemenu',
            name='date',
        ),
    ]
