# Generated by Django 4.2.5 on 2023-12-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_recipemenu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemenu',
            name='week_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
