# Generated by Django 4.2.5 on 2023-12-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_recipemenu_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemenu',
            name='week_day',
        ),
    ]
