# Generated by Django 4.2.5 on 2023-12-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_recipemenu_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemenu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
