# Generated by Django 4.2.5 on 2023-12-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_recipemenu_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeMenu',
        ),
    ]
