# Generated by Django 4.2.5 on 2023-12-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0010_alter_ingredients_options'),
        ('menu', '0014_delete_recipemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_recipe', to='menu.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.resipes')),
            ],
            options={
                'verbose_name': 'Репт в меню',
                'verbose_name_plural': 'Рецепты в меню',
            },
        ),
    ]
